CREATE TABLE IF NOT EXISTS USER (
    idUser INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT
);

CREATE TABLE IF NOT EXISTS MESSAGE (
    idMessage INTEGER PRIMARY KEY AUTOINCREMENT,
    nameUser INTEGER,
    content TEXT,
    date DATE,
    like INTEGER,
    FOREIGN KEY (nameUser) REFERENCES USER(name)
);
